#!/bin/bash

echo "==================================="
echo "==================================="
echo "========= composer-runner ========="
echo "==================================="
echo "==================================="
echo ""
echo ""

if [ -d "web" ] && [ -f "composer.json" ]; then
  echo "estás en el vhost:  "
  site="$(pwd)/web"
  vhost=${site%"/web"}
else
  echo "estás en el site: "
  site="$(pwd)"
  vhost=${site%"/web"}
fi

# echo "name:"
# read name
name=drupal-core-composer-project

# echo "database:"
# read database
database=drupal-core-composer-project

# echo "username:"
# read username
username=root

# echo "password:"
# read password
password=root

config_dir="../config/sync"

echo "site -> $site"
echo "vhost -> $vhost"
echo "name -> $name"
echo "database -> $database"
echo "username -> $username"
echo "password -> $password"
echo "config_dir -> $config_dir"

cd $vhost
echo "corrigiendo permisos"
# sudo chmod -R 777 .
# sudo chown -R user:user .

echo "composer update --with-dependencies"
# composer update --with-dependencies

echo ""

echo "generate theme"
cd $site/themes/custom/druparcheky_theme
echo $name
echo $site
bash $vhost/devscripts/theme-generate $name $site
exit

cd $vhost
echo "borrando carpetas .git..."
find ./ -name .git -type d -exec rm -fr {} \;
rm .gitignore .gitmodules

cd $site
# drush si druparcheky --db-url=mysql://root:root@localhost/$site --account-name=admin --account-mail=admin@$site.test --account-pass=admin --site-name=$site --site-mail=$site@$site.test -y --locale=es
drush si minimal --db-url=mysql://$username:$password@localhost/$database --account-name=admin --account-mail=admin@$site.test --account-pass=admin --site-name=$site --site-mail=$site@$site.test -y --locale=es

echo "inicializando git..."
cp example.gitignore .gitignore
git init

sudo chmod -R 777 .
drush fp

echo "

\$settings['config_sync_directory'] = '$config_dir';

" >> $site/sites/default/settings.php

echo "terminado, haga el primer commit"