#!/bin/bash

echo "==================================="
echo "==================================="
echo "========= composer-runner ========="
echo "==================================="
echo "==================================="
echo ""
echo ""


if [ -d "web" ] && [ -f "composer.json" ];
then
  echo "estás en el vhost:  "
  site="$(pwd)/web"
  vhost=${site%"/web"}
else
  echo "estás en el site: "
  site="$(pwd)"
  vhost=${site%"/web"}
fi


# echo "name:"
# read name
# name=drupal-core-composer-project

# echo "database:"
# read database
database=drupal-core-composer-project

# echo "username:"
# read username
username=root

# echo "password:"
# read password
password=root

config_dir="../config/sync"

echo "site -> $site"
echo "vhost -> $vhost"
# echo "name -> $name"
echo "database -> $database"
echo "username -> $username"
echo "password -> $password"
echo "config_dir -> $config_dir"


cd $vhost

git submodule init
git submodule update
cp *.code-workspace.example $name.code-workspace

sudo chmod -R 777 .

rm -fr vendor
composer update --with-dependencies

cp $site/sites/default/default.settings.php $site/sites/default/settings.php
cp $site/sites/default/default.services.php $site/sites/default/services.php

echo "

\$databases['default']['default'] = array (
  'database' => '$database',
  'username' => '$username',
  'password' => '$password',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
\$settings['config_sync_directory'] = '$config_dir';


" >> $site/sites/default/settings.php
