#!/bin/bash

echo "==================================="
echo "==================================="
echo "====> composer-pre-install-cmd"

echo "==> Aplicando permisos 777 antes de actualizar para evitar errores"
# sudo chmod -R 777 .
# sudo chown -R user:user .
echo "==================================="
